In [537]:
import numpy as np

In [538]:
import re

def clean_tweet(tweet: str) -> str:
    # take out URLs
    tweet = re.sub("http.*(\s|$)", ' ', tweet)
    # take out mentions
    tweet = re.sub("@[^\s]+", ' ', tweet)
    # take out hashtags
    tweet = re.sub("#[^\s]+", ' ', tweet)
    # take out all characters outside of those we enumerate
    tweet = re.sub("[^\da-zA-ZáéíóúüñÁÉÍÑÓÚÜ¿?¡!.,;#:<>()'“”\"\s]", ' ', tweet)
    # lowercase everything
    tweet = tweet.lower()
    # reset spaces
    tweet = re.sub("\s+", ' ', tweet)
    tweet = re.sub("^\s+", '', tweet)
    tweet = re.sub("\s$", '', tweet)
    return tweet

In [539]:
import random

# spotchecking loop to check that clean_tweet() works
with open('lid_train_lines.txt', 'r') as input_file:
    for line in input_file:
        if random.random() < 0.0005:
            line = line.strip()
            print(line)
            print(clean_tweet(line))

El vlog de hoy , pequeñas sorpresas en el correo : omg GORRAS !! https://t.co/crJzDhip7O
el vlog de hoy , pequeñas sorpresas en el correo : omg gorras !!
@ritacm01 probablemente 🌝
probablemente
ñeta hice eye contact con la profesora y me mandó a hablar
ñeta hice eye contact con la profesora y me mandó a hablar
ESTE CABRON ME LA EXPLOTA CADA VEZ QUE SE METE DONDE NADIE LO FUCKING LLAMA !!
este cabron me la explota cada vez que se mete donde nadie lo fucking llama !!
@Jona_Boy13 vengo por el weewee
vengo por el weewee
Ok yaaa enough Duranguense tweets 4 2day a llamarle a Mi Reina Hermosa hija d mi pinshi suegra lol k su voz es lo k me completa Mis Noches ♥
ok yaaa enough duranguense tweets 4 2day a llamarle a mi reina hermosa hija d mi pinshi suegra lol k su voz es lo k me completa mis noches
been wahcing cops for a minute now haaha
been wahcing cops for a minute now haaha
Held accountable : Ser responsable/ Hacerse responsable . I do n't want to be held accountable for your bad actions 

In [540]:
clean_lines = []

with open('lid_train_lines.txt', 'r') as input_file:
    for line in input_file:
        clean_lines.append(clean_tweet(line))

In [541]:
len(clean_lines)

21030

In [542]:
random.seed(a=50)

In [543]:
chosen_tweets = random.choices(clean_lines, k=100)

In [544]:
chosen_tweets

['mañana viernes wilfrido vargas ..',
 'u love me',
 'so original .. .',
 'whats up with nature',
 'aguanta tu ritmo .',
 "i do n't like ( xxx ) people , they always think they 're right and do n't listen to anything else . ( testarudo a obstinado a tercho a )",
 'ni pinches moscas pescas tu mondaooo',
 'new week , be kind and sweet ! vestido sahara',
 'no puedo bregar con la gente stalker',
 'a cantarle las mañanitas ala virgencita',
 'el vlog de hoy aunque sea tarde , pequeñas cenas agradables : el día más feliz de mi vida',
 'all bad',
 'no es sinónimo pero significa lo mismo , i get out of work at 6 pm , creo q esto es lo q querías decir :)',
 'blusa violeta y sus diferentes estampados ! escoge tu color favorito made in ecuador',
 '¡¡ nuevo vídeo !! en esta ocasión , un famoso presentador de tv me hace una durísima entrevista .. . ¡ se .. .',
 'get the hang of it : acostumbrarse a esto poder dominarlo person 1 : this new job is so stressful . person 2 : you ll get the hang of it .'

In [545]:
for chosen_tweet in chosen_tweets:
    print (chosen_tweet)

mañana viernes wilfrido vargas ..
u love me
so original .. .
whats up with nature
aguanta tu ritmo .
i do n't like ( xxx ) people , they always think they 're right and do n't listen to anything else . ( testarudo a obstinado a tercho a )
ni pinches moscas pescas tu mondaooo
new week , be kind and sweet ! vestido sahara
no puedo bregar con la gente stalker
a cantarle las mañanitas ala virgencita
el vlog de hoy aunque sea tarde , pequeñas cenas agradables : el día más feliz de mi vida
all bad
no es sinónimo pero significa lo mismo , i get out of work at 6 pm , creo q esto es lo q querías decir :)
blusa violeta y sus diferentes estampados ! escoge tu color favorito made in ecuador
¡¡ nuevo vídeo !! en esta ocasión , un famoso presentador de tv me hace una durísima entrevista .. . ¡ se .. .
get the hang of it : acostumbrarse a esto poder dominarlo person 1 : this new job is so stressful . person 2 : you ll get the hang of it .
clase de text
voy a empezar a pedirle trabajos a la gente como

In [546]:
DISACCENT_MAP = {'á': 'a', 'é': 'e', 'í': 'i', 'ó': 'o', 'ú': 'u', 'ü': 'u', 'ñ': 'n'}

def drop_accents(tweet: [str], drop_probability: float=1.0) -> [str]:
    output = []
    for c in tweet:
        if c in DISACCENT_MAP and random.random() < drop_probability:
            output.append(DISACCENT_MAP[c])
        else:
            output.append(c)
    return output

In [547]:
example = 'jajajaajaja yo odio la palabra " moción " con mi vida entera después de la estupidez de huelga esa'
''.join(drop_accents(example, 0.5))

'jajajaajaja yo odio la palabra " mocion " con mi vida entera despues de la estupidez de huelga esa'

In [548]:
len(clean_lines)

21030

In [549]:
VOWELS_SET = set("aeiouáéíóúü")

def drop_vowels(tweet: [str], drop_probability: float=1.0) -> [str]:
    output = []
    for c in tweet:
        if c in VOWELS_SET and random.random() < drop_probability:
            continue
        output.append(c)
    return output

In [550]:
''.join(drop_vowels(example, 0.1))

'jajajajaja yo odo la palabr " moción " con m vida entera después de la estpidez de huelga esa'

In [551]:
def repeat_vowels(tweet: [str], repeat_probability=0.05, max_repeat=6) -> [str]:
    output = []
    for c in tweet:
        if c in VOWELS_SET and random.random() < repeat_probability:
            for _ in range(random.randint(1, max_repeat)):
                output.append(c)
        output.append(c)
    return output

In [552]:
''.join(repeat_vowels(example))

'jajajaajaaaaaaja yo odio la palabra " moción " con miiii vida entera después de la estupidez dee huelga esa'

In [553]:
CREATIVE_SUB_MAP = {'c': 's', 's': 'z', 'b': 'v', 'v': 'b'}

def substitute_creatively(tweet: [str], substitution_probability=0.1):
    output = []
    for c in tweet:
        if c in CREATIVE_SUB_MAP and random.random() < substitution_probability:
            output.append(CREATIVE_SUB_MAP[c])
        else:
            output.append(c)
    return output

In [554]:
''.join(substitute_creatively(example))

'jajajaajaja yo odio la palabra " moción " con mi vida entera después de la estupidez de huelga eza'

In [555]:
def simulate_creative_misspellings(tweet: [str]) -> [str]:
    if random.random() < 0.7:
        return repeat_vowels(tweet)
    else:
        return substitute_creatively(tweet)

In [556]:
def simulate_intentional_shortenings(tweet: [str]) -> [str]:
    input_tokens = ''.join(tweet).split(' ')
    output_tokens = []
    for token in input_tokens:
        if random.random() < 0.3:
            output_tokens.append(''.join(drop_vowels(list(token), 0.5)))
        else:
            output_tokens.append(token)
    return list(' '.join(output_tokens))

In [557]:
''.join(simulate_intentional_shortenings(example))

'jajajaajaja yo odio l palabra " moción " con mi vida entera despus d la estupidez de huelga esa'

In [558]:
ALPHABET_L = list("abcdefghijklmnopqrstuvwxyzáéíóúüñ")
ALPHABET_S = set(ALPHABET_L)
print(ALPHABET_L)
print(ALPHABET_S)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'á', 'é', 'í', 'ó', 'ú', 'ü', 'ñ']
{'j', 'h', 'b', 'ó', 'ñ', 'g', 'm', 'í', 'á', 'd', 'x', 'ü', 'p', 'c', 'e', 'v', 'o', 'l', 'n', 'é', 'f', 't', 'ú', 'k', 'i', 'r', 'a', 'w', 'y', 'u', 'q', 's', 'z'}


In [559]:
def simulate_bona_fide_spelling_mistakes(tweet: [str], modify_rate=0.1) -> [str]:
    # equally add, omit, or substitute each character for a total probability of modify_rate
    add_cmf_val = modify_rate / 3
    omit_cmf_val = 2 * modify_rate / 3
    substitute_cmf_val = modify_rate
    
    output = []
    for c in tweet:
        r = random.random()
        if r < add_cmf_val:
            output.append(c)
            output.append(random.choice(ALPHABET_L))
        elif r < omit_cmf_val:
            continue
        elif c in ALPHABET_S and r < substitute_cmf_val:
            # we don't apply substitutions to non-alpha
            output.append(random.choice(ALPHABET_L))
        else:
            output.append(c)
    return output

In [560]:
''.join(simulate_bona_fide_spelling_mistakes(example))

'jajajaajaja vo odio la palabra " moción " con mi vida etea después dte lx esteupidez de huega esa'

In [561]:
def identity(tweet: [str]) -> [str]:
    return tweet

In [562]:
DEFAULT_WEIGHT_MAP = [[14, simulate_creative_misspellings],
                      [13, drop_accents],
                      [10, simulate_intentional_shortenings],
                      [8, simulate_bona_fide_spelling_mistakes],
                      [10, identity]]

class DisjointNoiser:
    def __init__(self, weight_map=DEFAULT_WEIGHT_MAP):
        self.weight_map = weight_map
        total = sum([self.weight_map[i][0] for i in range(len(self.weight_map))])
        # we normalize the pmf
        for i in range(len(self.weight_map)):
            self.weight_map[i][0] /= total
        # we make the pmf into a cmf
        for i in range(1, len(self.weight_map) - 1):
            self.weight_map[i][0] += self.weight_map[i - 1][0]
        self.weight_map[-1][0] = 1.0  # so as not to worry about rounding errors

    def add_noise(self, tweet: [str]) -> [str]:
        """Applies at most 1 kind of noising to the tweet according to the weights in the weight map.
        Each 'noising' could alter the tweet in multiple places or not at all.
        """
        tweet = list(tweet)
        my_random_number = random.random()
        for max_prob, noise_function in self.weight_map:
            if my_random_number < max_prob:
                # print('calling', noise_function)
                return noise_function(tweet)

In [563]:
noiser = DisjointNoiser()
for _ in range(10):
    noiser.add_noise('abcd')

In [564]:
noiser = DisjointNoiser()
for _ in range(10):
    print(''.join(noiser.add_noise(example)))
    print()

jjajjaja yo odio la palabra " moción " con mi vida entera después de la estupidez de huelga esa

jajajaajaja yo odio l palabra " moción " con m vida entera dspués de la stpidz de huelga esa

jajajaajaja yo odio la palabra " moción " con mi vida entera después de la estupidez de huelga esa

jajajaajaja yo odio la palabra " mocion " con mi vida entera despues de la estupidez de huelga esa

jajajaajaja yo odio la palabra " moción " con mi vida entera después de la estupidez de huelga esa

jajajaajaja yo odio la palabra " moción " con mi vida entera después de la estupidez de huelga esa

jajajajfja yo odio la ypalabra " oción " con mi vviada etera después de la estufpidez de huelga qsa

jajajaajaja yo odio la palabra " mción " con mi vd entera desps de la estupidez de hulga esa

jjajaajajay yo diá la alabra " moción " con mi vida entera después de la estoupidez de huelga es

jajajaajavja y odiolj plabra " moción c" csn mi visa entera dñespué de la estupidez de helga xsa



In [565]:
len(clean_lines)

21030

In [566]:
max(len(line) for line in clean_lines)

154

In [567]:
sum(len(line) for line in clean_lines) / len(clean_lines)

49.6810746552544

In [568]:
clean_medium_lines = [line for line in clean_lines if 10 < len(line) < 100]

In [569]:
len(clean_medium_lines)

16908

In [570]:
VOCAB_L = ALPHABET_L + list("0123456789¿?¡!.,;#:<>()'“”\" ") + ['<EOT>', '<PAD>']
print(VOCAB_L)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'á', 'é', 'í', 'ó', 'ú', 'ü', 'ñ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '¿', '?', '¡', '!', '.', ',', ';', '#', ':', '<', '>', '(', ')', "'", '“', '”', '"', ' ', '<EOT>', '<PAD>']


In [571]:
VOCAB_TO_INT = {v: i for i, v in enumerate(VOCAB_L)}

In [572]:
example_ints = [VOCAB_TO_INT[c] for c in example]

In [573]:
print(example_ints)

[9, 0, 9, 0, 9, 0, 0, 9, 0, 9, 0, 60, 24, 14, 60, 14, 3, 8, 14, 60, 11, 0, 60, 15, 0, 11, 0, 1, 17, 0, 60, 59, 60, 12, 14, 2, 8, 29, 13, 60, 59, 60, 2, 14, 13, 60, 12, 8, 60, 21, 8, 3, 0, 60, 4, 13, 19, 4, 17, 0, 60, 3, 4, 18, 15, 20, 27, 18, 60, 3, 4, 60, 11, 0, 60, 4, 18, 19, 20, 15, 8, 3, 4, 25, 60, 3, 4, 60, 7, 20, 4, 11, 6, 0, 60, 4, 18, 0]


In [574]:
def pad_tweet_batch(tweet_batch, max_tweet_length_in_batch):
    """Pad tweets with <PAD> so that each sentence of a batch has the same length"""
    return [tweet + [VOCAB_TO_INT['<PAD>']] * (max_tweet_length_in_batch - len(tweet)) for tweet in tweet_batch]

In [710]:
def get_batches(tweets, noiser, batch_size):
    
    for batch_i in range(0, len(tweets) // batch_size):
        start_i = batch_i * batch_size
        tweets_batch = tweets[start_i:start_i + batch_size]
        tweets_batch_noised = [noiser.add_noise(tweet) for tweet in tweets_batch]
        
        tweets_batch_ints = [[VOCAB_TO_INT[v] for v in tweet] for tweet in tweets_batch]
        tweets_batch_noised_ints = [[VOCAB_TO_INT[v] for v in tweet] for tweet in tweets_batch_noised]
        
        tweets_batch_eot = [tweet + [VOCAB_TO_INT['<EOT>']] for tweet in tweets_batch_ints]
        tweets_batch_noised_eot = [tweet + [VOCAB_TO_INT['<EOT>']] for tweet in tweets_batch_noised_ints]
        
        pad_tweets_batch = np.array(pad_tweet_batch(tweets_batch_eot,
                                                    max([len(tweet) for tweet in tweets_batch_eot])))
        pad_tweets_noised_batch = np.array(pad_tweet_batch(tweets_batch_noised_eot,
                                                           max([len(tweet) for tweet in tweets_batch_noised_eot])))
        
        pad_tweets_lengths = [len(tweet) for tweet in pad_tweets_batch]
        pad_tweets_noised_lengths = [len(tweet) for tweet in pad_tweets_noised_batch]
        
        # yield(pad_tweets_noised_batch, pad_tweets_batch, pad_tweets_noised_lengths, pad_tweets_lengths)
        yield [pad_tweets_noised_batch, pad_tweets_batch]

In [711]:
clean_sorted_medium_lines = sorted(clean_medium_lines, key=lambda t: len(t))

In [712]:
gb = get_batches(clean_sorted_medium_lines, noiser, batch_size=8)

In [713]:
print(next(gb))

[array([[ 2, 20,  0, 13,  3, 14, 60, 13, 14, 60, 44, 61],
       [ 6, 17,  0,  2,  8,  0, 18, 18, 60, 51, 55, 61],
       [ 9,  0,  8,  0,  9,  0,  9,  0,  9,  9,  0, 61],
       [ 5,  0, 11, 19,  0,  1,  0, 18, 60, 19, 20, 61],
       [13,  8, 60,  8,  3,  4,  0, 60, 46, 60, 51, 61],
       [ 3, 14, 22, 13, 60,  9,  0,  9,  0,  9,  0, 61],
       [14, 13, 19,  0,  0,  0, 60,  9,  0,  9,  0, 61],
       [19,  0, 10,  4, 60,  0, 60,  7,  8, 13, 19, 61]]), array([[ 2, 20,  0, 13,  3, 14, 60, 13, 14, 60, 44, 61],
       [ 6, 17,  0,  2,  8,  0, 18, 18, 60, 51, 55, 61],
       [ 9,  0,  9,  0,  9,  0,  9,  0,  9,  9,  0, 61],
       [ 5,  0, 11, 19,  0,  1,  0, 18, 60, 19, 20, 61],
       [13,  8, 60,  8,  3,  4,  0, 60, 46, 60, 51, 61],
       [ 3, 14, 22, 13, 60,  9,  0,  9,  0,  9,  0, 61],
       [14, 13, 19,  0,  0,  0, 60,  9,  0,  9,  0, 61],
       [19,  0, 10,  4, 60,  0, 60,  7,  8, 13, 19, 61]])]


In [714]:
pad_tweets_noised_batch, pad_tweets_batch, pad_tweets_noised_lengths, pad_tweets_lengths = next(gb)

ValueError: not enough values to unpack (expected 4, got 2)

In [715]:
print(pad_tweets_noised_batch)

[[ 8 60  0  3 14 17  4 60 24 14 20 61]
 [14  7 60 14 10  0 24 60 47 60 47 61]
 [22 14  0  7  7  7  7  7 60  2 23 61]
 [ 8 19 18 60 17  4  3 60 11 14 11 61]
 [ 7  0  7  0  7  7  0  7  0  7  2 61]
 [14  7 60 14  7 60 14  7 60 14  7 61]
 [14 13 19  0 60 11  0 60 44 44 44 61]
 [10  4 12  0 11 14 18 18 18 18 18 61]]


In [716]:
print(pad_tweets_batch)

[[ 8 60  0  3 14 17  4 60 24 14 20 61]
 [14  7 60 14 10  0 24 60 47 60 47 61]
 [22 14  0  7  7  7  7  7 60  2 23 61]
 [ 8 19 18 60 17  4  3 60 11 14 11 61]
 [ 7  0  7  0  7  7  0  7  0  7  0 61]
 [14  7 60 14  7 60 14  7 60 14  7 61]
 [14 13 19  0 60 11  0 60 44 44 44 61]
 [10  4 12  0 11 14 18 18 18 18 18 61]]


In [717]:
from keras.models import Sequential
from keras.layers import Activation, Dense, Dropout, LSTM, RepeatVector
print(keras.__version__)

2.1.2


In [718]:
model = Sequential()

DROPOUT = RECURRENT_DROPOUT = 0.8
HIDDEN_SIZE = 50

model.add(LSTM(units=HIDDEN_SIZE, input_shape=(None, len(VOCAB_TO_INT)),
               kernel_initializer="he_normal", dropout=DROPOUT, recurrent_dropout=RECURRENT_DROPOUT))

output_len = 100

model.add(RepeatVector(output_len))

LAYERS = 2

for _ in range(LAYERS):
    model.add(LSTM(HIDDEN_SIZE, return_sequences=True,
                   kernel_initializer="he_normal", dropout=DROPOUT, recurrent_dropout=RECURRENT_DROPOUT))
    
model.add(Dense(len(VOCAB_TO_INT), kernel_initializer="he_normal"))

model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [720]:
BATCH_SIZE = 32

batches = get_batches(clean_sorted_medium_lines, noiser, batch_size=BATCH_SIZE)

model.fit(batches, steps_per_epoch=len(clean_sorted_medium_lines) // BATCH_SIZE, epochs=1)

TypeError: Error when checking model input: data should be a Numpy array, or list/dict of Numpy arrays. Found: <generator object get_batches at 0x7fa700ea66d0>...